config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'comments#index'
  resources :comments
  get 'about', to: 'comments#about'  
  get 'all', to: 'comments#all'

  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :feedback, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comment = Comment.order("RANDOM()").first
    @image = Image.order("RANDOM()").first
  end

  def create
    @comment = Comment.create(comment_params)
    if @comment.invalid?
      flash[:error] = '<strong>Could not save.</strong> Invalid data, please try again.'
    end
    redirect_to root_path
  end

  def about
  end

  def all
    @comment = Comment.all
  end

  private

  def comment_params
    params.require(:comment).permit(:feedback, :author)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @image = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    Image.create(image_params)
    redirect_to root_path
  end

  private

  def image_params
    params.require(:image).permit(:caption, :author, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/about.html.erb
<div class="col-10 offset-1">
  <center>
  <h1>About This Bootcamp Quiz</h1>

  <p>
    This page was built by <a target="-blank" href="https://robynwang.netlify.com">Robyn</a> for her bootcamp quizes. She is buiding this page to test her ability in following the steps to building a working web application without the help of others. Hopefully she's got the right idea and it works!
  </p>
  </center>
</div>

app/views/comments/all.html.erb
<div class="col-10 offset-1">
  <h1><center>Full List of Random Quotes</center></h1>
</div>

<br />

<% @comment.each do |comment| %>
  <p><%= comment.feedback %><br />
    <i div class="float-right">-<%= comment.author %></i>
  </p>
  <br />
<% end %>

app/views/comments/index.html.erb
<center>
  <h1>Welcome to Robyn's Quiz Attempts!</h1>
  <p>La dee dah, blah blah blah</p>
</center>

<br />
  <p><%= @comment.feedback %> </p>
  <i>- <%= @comment.author %></i>
<br />
<br />

  <%= image_tag @image.picture.to_s, class: 'img-fluid' %>
  <p><%= @image.caption %><br />
    <i>-<%= @image.author %></i>
  </p>

<br />
<br /><br />

    <div class="text-center all">
      <%= link_to 'View all Quotes', all_path, class: 'btn btn-outline-success' %> &nbsp; &nbsp;
      <%= link_to 'View all Memes', images_path, class: 'btn btn-outline-success' %>
    </div>



<br class="clear" />
<br />
<br />
<br />

app/views/images/index.html.erb
<div class="col-10 offset-1">
  <h1><center>Compilation of Memes</center></h1>
</div>

<br />

<% @image.each do |image| %>
  <p><%= image.caption %><br />
  <i>-<%= image.author %></i></p>
  <br />
  <center><%= image_tag image.picture.to_s, class: 'img-fluid' %></center>
  <br />
<% end %>

<br /><br /><br />
<div class="clear"></div>

app/views/images/new.html.erb
<center><h1> Submit a Meme </h1></center>
<div class="image_form">  
  <%= simple_form_for @image do |f| %>
    <%= f.input :caption %>
    <%= f.input :author %>
    <%= f.input :picture %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
        <div class="col-3 logo">
          <%= link_to root_path, class: 'logo' do %>
              <br />
              BOOTCAMP
              <br />
              QUIZ
          <% end %>
        </div>
        <div class="col-4 offset-1 hidden-xs-down slogan">
          How will she do? We will see!
        </div>
        <div class="col offset-1 col-sm offset-sm-1 links">
           <!-- Button trigger modal -->
            <%= link_to 'Contribute Comment', '#', data: {toggle: 'modal', target: '#myModal'} %>
            &nbsp;&nbsp;
            <%= link_to 'Contribute Meme', new_image_path %>
            &nbsp;&nbsp;
            <%= link_to 'About', about_path %>
        </div>
      </header>


      <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Enter Your Comments Here</h4>
          </div>
          <%= simple_form_for Comment.new do |f| %>
            <div class="modal-body">
                <%= f.input :feedback, placeholder: "What are your thoughts?" %>
                <br />
                <%= f.input :author, placeholder: "What is your name?" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Submit', class: 'btn btn-outline-success' %>
            </div>
            <% end %>
        </div>
      </div>
    </div>

      <hr />
      <br class="clear" />

      <div class="container">
        <% if flash[:error].present? %>
          <div class="col-10 offset-1 alert alert-danger">
            <%= flash[:error].html_safe %>
          </div>
        <% end %>
        <%= yield %>
      </div>

      <div class="footer">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-6 date-created">
              August 2019
            </div>
            <div class="col-12 col-sm-6 footer-blurb">
              Powered by <a href="https://robynwang.netlify.com">Robyn Wang</a><br />
            </div>
          </div>
        </div>
      </div>

  </body>
</html>

<meta name="viewport" content="width=device-width, initial-scale=1">